name: TimoCloud
version: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}
author: TimoCrafter
main: cloud.timo.TimoCloud.bukkit.TimoCloudBukkit
softdepend: [Multiverse-Core]
commands:
  timocloudbukkit:
    aliases: [tcb]
  signs: