name: TimoCloud
version: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}
author: TimoCrafter
main: at.TimoCraft.TimoCloud.llIllllIIIIlIlIl.llIllllIIIIlIlIl
softdepend: [Multiverse-Core]
commands:
  timocloudbukkit:
    aliases: [tcb]
  signs:
  sendbungee: