name: TimoCloud
version: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}
author: TimoCrafter
main: at.TimoCraft.TimoCloud.a.a
commands:
  timocloudbukkit:
    aliases: [tcb]
  signs:
  sendbungee: